// groceries.js
const groceries = [
  {
    name: "Bananas",
    category: "Produce",
    price: 1.29,
    quantity: 6,
    unit: "each",
    organic: true,
  },
  {
    name: "Milk",
    category: "Dairy",
    price: 3.49,
    quantity: 1,
    unit: "gallon",
    organic: false,
  },
  {
    name: "Bread",
    category: "Bakery",
    price: 2.99,
    quantity: 1,
    unit: "loaf",
    organic: false,
  },
  {
    name: "Ground Beef",
    category: "Meat",
    price: 6.99,
    quantity: 1,
    unit: "pound",
    organic: false,
  },
  {
    name: "Spinach",
    category: "Produce",
    price: 3.99,
    quantity: 1,
    unit: "bag",
    organic: true,
  },
  {
    name: "Cheddar Cheese",
    category: "Dairy",
    price: 4.29,
    quantity: 8,
    unit: "ounces",
    organic: false,
  },
  {
    name: "Chicken Breast",
    category: "Meat",
    price: 8.99,
    quantity: 2,
    unit: "pounds",
    organic: false,
  },
  {
    name: "Apples",
    category: "Produce",
    price: 4.99,
    quantity: 3,
    unit: "pounds",
    organic: true,
  },
  {
    name: "Rice",
    category: "Pantry",
    price: 2.49,
    quantity: 1,
    unit: "bag",
    organic: false,
  },
  {
    name: "Yogurt",
    category: "Dairy",
    price: 5.99,
    quantity: 6,
    unit: "pack",
    organic: true,
  },
];

module.exports = groceries;
